name: Quality Pipeline

on:
  pull_request:
    branches: [master]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    needs: setup  
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test-command: "npx playwright test"