name: Setup Environment

on:
  workflow_call:
    outputs:
      cache-key:
        description: "cache key for setup"
        value: ${{ jobs.setup.outputs.cache-key }}

jobs:
  setup:
    name: Install Dependencies & Prepare Environment
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-key }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browsers
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Save cache key as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache-key
          path: cache-key.txt