name: Run Tests

on:
  workflow_run:
    workflows: [setup]
    types:
      - completed

  workflow_call:
    inputs:
      test-command:
        description: "run tests command"
        required: false
        default: "npx playwright test"
        type: string
      test-path:
        description: "tests path"
        required: false
        default: "./src/tests"
        type: string

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run tests
        run: ${{ inputs.test-command }}
        env:
          INATURALIST_API_TOKEN: ${{ secrets.INATURALIST_API_TOKEN }}  //get on https://www.inaturalist.org/users/api_token and put here https://github.com/shtepbraiter/inaturalist-quality-control-pipeline/settings/secrets/actions

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/